/** @format */
import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './component/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './stories/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
          950: '#082f49',
        },
        secondary: {
          50: '#f5f3ff',
          100: '#ede9fe',
          200: '#ddd6fe',
          300: '#c4b5fd',
          400: '#a78bfa',
          500: '#8b5cf6',
          600: '#7c3aed',
          700: '#6d28d9',
          800: '#5b21b6',
          900: '#4c1d95',
          950: '#2e1065',
        },
        chart1: 'var(--chart-1)',
        chart2: 'var(--chart-2)',
        chart3: 'var(--chart-3)',
        chart4: 'var(--chart-4)',
        chart5: 'var(--chart-5)',
        sidebar: 'var(--sidebar)',
        sidebarForeground: 'var(--sidebar-foreground)',
        sidebarPrimary: 'var(--sidebar-primary)',
        sidebarPrimaryForeground: 'var(--sidebar-primary-foreground)',
        sidebarAccent: 'var(--sidebar-accent)',
        sidebarAccentForeground: 'var(--sidebar-accent-foreground)',
        sidebarBorder: 'var(--sidebar-border)',
        sidebarRing: 'var(--sidebar-ring)',
      },
      borderRadius: {
        sm: '12px',
        md: '14px',
        lg: '24px',
        xl: '36px',
        full: '9999px',
      },
      padding: {
        sm: '12px',
        md: '14px',
        lg: '24px',
        xl: '36px',
        full: '9999px',
      },
      gap: {
        sm: '12px',
        md: '14px',
        lg: '24px',
        xl: '36px',
        full: '9999px',
      },
      margin: {
        sm: '12px',
        md: '14px',
        lg: '28px',
        xl: '36px',
        full: '9999px',
      },
      spacing: {
        sm: '12px',
        md: '14px',
        lg: '28px',
        xl: '36px',
        full: '9999px',
        1: '0.25rem',
        2: '0.5rem',
        3: '0.75rem',
        4: '1rem',
        5: '1.25rem',
        6: '1.5rem',
        8: '2rem',
        10: '2.5rem',
        12: '3rem',
      },
      keyframes: {
        'circle-draw': {
          '0%': { strokeDashoffset: '565.48' },
          '100%': { strokeDashoffset: '0' },
        },
        'tick-draw': {
          '0%': { strokeDashoffset: '240' },
          '100%': { strokeDashoffset: '0' },
        },
      },
      animation: {
        'circle-draw': 'circle-draw 1s ease-in-out forwards',
        'tick-draw': 'tick-draw 0.8s ease-out forwards',
      },
    },
  },

  plugins: [],
};
export default config;
